image: docker:19.03.1
services:
  - docker:19.03.1-dind

variables:
  DOCKER_TLS_CERTDIR: /builds/cert
  DOCKER_DRIVER: overlay2

stages:
#  - tests
  - deploy

deploy_to prod:
  stage: deploy
  before_script:
    - 'which ssh-agent || ( apk add openssh )'
    - eval $(ssh-agent -s)
    - echo "$SSH_PROD_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  only:
    - devops/init
  script:
    - ssh -p${SSH_PORT} ${SSH_USER}@${PROD_SERVER} "cd ${PROJECT_PATH} &&
      make pull &&
      exit"
  allow_failure: false
