version: '3.7'
services:
  nginx:
    container_name: cdaem_nginx
    build:
      context: ..
      dockerfile: ./docker/nginx/Dockerfile
    volumes:
      - ../app:/app
      - ./nginx:/etc/nginx/conf.d
      - ./nginx/ssl:/ssl
    env_file:
      - .docker.env
    command: /bin/sh -c "envsubst '$$SERVER_NAME $$SERVER_NAME_WILD $$SERVER_NAME_CONTROL' < /etc/nginx/conf.d/default.prod.conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    restart: always

  app:
    container_name: cdaem_php
    build:
      context: ..
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ../app:/app
      - ./php/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./php/php-fpm.conf:/usr/local/etc/php-fpm.d/php-fpm.conf
      - ./cron:/etc/cron
    restart: always
    working_dir: /app

  node:
    container_name: cdaem_node
    working_dir: /app
    build:
      context: ..
      dockerfile: ./docker/node/Dockerfile
    volumes:
      - ../app:/app